### ISSUE TITLE
saas-cache should not be part of the repository

### ISSUE THREAD

**Issue by DanieleVistalli** [hclcnx/cnx-custom-theme#53]
### Steps to reproduce the issue

There's no need to reproduce, .saas-cache files should not be in the repository, the built output is in "css" folder so we need to delete .saas-cache and add .saas-cache to git-ignore

A clean repository makes things easier for everybody.

**Comment by hclcnxdev** [comment]
We removed the .sass-cache directory with PR #54.

**Comment by DanieleVistalli** [comment]
This is great, tomorrow I pick the change and pass on to production. I'm positively surprised you picked this so fast !!!!
