### ISSUE TITLE
File Upload in Community

### ISSUE THREAD

**Issue by wannesrams** [hclcnx/cnx-custom-theme#64]
When uploading a new file in a Community, the drag and drop box is not aligned properly and is tiny

### Steps to reproduce the issue

 go to a Community, go to the Files section ( Not the overview page  widget) in the community and select new Upload

### Screen shots

<img width="1813" alt="Screenshot 2021-08-12 at 14 46 15" src="https://user-images.githubusercontent.com/28135668/132345890-1dd86441-4372-4a67-add0-50dc128754e9.png">

### DESIGN DOCUMENTS (Specs, Playbacks, Research)
ICS Design Guide: https://design-guide.w3ibm.mybluemix.net/resources/component-status

**Comment by ms2art** [comment]
Hi. I'll take a look at this. I'm unable to assign this issue to myself; if you can, that would be great.

**Comment by ms2art** [comment]
@wannesrams This should be resolved via PR https://github.com/hclcnx/cnx-custom-theme/pull/65

**Comment by umeli** [comment]
I can confirm that it's solved in communities.
![Selection_731](https://user-images.githubusercontent.com/710539/133210932-68a3addb-4b0b-45d9-ab1d-9c7192796692.png)
